### ISSUE TITLE
Can't find any rooms in Teamcity

### ISSUE THREAD

**Issue by ysmei** [parautenbach/TeamCity-HipChat-Notifier#67]
I just set up the notifier on Teamcity using the API url and a token I created from my user that has "View Room" and "Send Notification" permissions. When I press test connection, it is successful. However I am unable to see any rooms from the drop down lists. How can I specify a room that I want to send notifications to?
![efwf](https://cloud.githubusercontent.com/assets/16123906/11542784/1335d9ec-9907-11e5-9c76-6927a61c2afa.PNG)

**Comment by raoulus** [comment]
Same for me

**Comment by parautenbach** [comment]
After entering the credentials and testing the connection, you need to save the settings, which will reload the page and populate the rooms. I need to improve that behaviour at some point (e.g. forcing a reload of rooms, just like one can reload the emoticons from the admin page).

**Comment by ysmei** [comment]
I've pressed "Save" and "Save to reload" multiple times making sure the connection is successful after each save and still get no rooms. I've also tried specifying a room number in the API URL and while it connects successfully, there are still no rooms to choose from.

**Comment by parautenbach** [comment]
Could you enable [debug logging](https://github.com/parautenbach/TeamCity-HipChat-Notifier#developers) please?

**Comment by ysmei** [comment]
Sorry I'm having a bit of trouble understanding the instructions. My current directory where Teamcity is installed is in var/Teamcity/data and the plugin is installed in var/Teamcity/data/plugins/.unpacked. Where should I be looking to enable the logging?

**Comment by parautenbach** [comment]
The config file you need to update is the TeamCity XML config file, typically in `<TEAMCITY_HOME>/conf/teamcity-server-log4j.xml` (it depends on your installation and OS). Just edit the file and add the snippets as described. The logs will then be in the server's log directory (`./logs`, on the same level as `./conf`).

**Comment by ysmei** [comment]
Okay I found the file. Do I need to reboot the server after editing the file? What tests should I run before checking the log?

**Comment by parautenbach** [comment]
You only need to restart TeamCity, I think (it may even be reloading the config at runtime so it may not even be necessary). Just do what you did before that didn't work, and check if there is a log file. If not, restart TeamCity, perform the steps again, and check the log again.

**Comment by ysmei** [comment]
[hipchat.txt](https://github.com/parautenbach/TeamCity-HipChat-Notifier/files/52214/hipchat.txt)
This is the log I got, I tried the connection multiple ways.

**Comment by chriszacny** [comment]
Just as a FYI - I'm seeing this too. (No rooms displayed / able to be selected). However, this plugin has been working fine up until now (roughly 1 year). Perhaps HipChat changed something on their end?

**Comment by mrvvV** [comment]
Hey @parautenbach, any updates?

**Comment by ShaneWF** [comment]
Noticing the same on ours.

**Comment by edandersen** [comment]
+1

**Comment by parautenbach** [comment]
My sincerest apologies for such a long delay before responding (due to personal circumstances). 

I've tested this again now using TC v9.1.1 and plugin v0.9.2 and the rooms get loaded correctly. 

The `hipchat.txt` log attached higher up does not contain any errors. Are you sure you copied the log that corresponds with when you tried to load rooms on the admin page (by loading the admin config page)? It could be a problem with your token scope. Atlassian changed the mechanism quite a bit and there were cases where they expired tokens, but I'm guessing they also assigned default scopes in some cases. Please refer to #52 and #62 for some help on choosing the correct scopes. 

Are there any other symptoms or errors any of you can note to help debug this?

![screen shot 2016-01-12 at 21 14 19](https://cloud.githubusercontent.com/assets/743320/12274005/8300decc-b971-11e5-81cd-9bd0c7a21532.png)

**Comment by dragon788** [comment]
I've used 4 permissions from the API, `Send Message, Send Notification, View Group, View Room`. This has everything working for me.
